name:  Hello
on:
  push:
   branches:
   - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  name: Checkout repository
      uses: actions/checkout@v4
    steps:
    -  name: print Hello
       run: echo "Hello"
    -  name: print current directory
       run: pwd
    -  name: print current user
       run: whoami
    -  name: print Hostname
       run:  hostname
    -  name: print date
       run: date
    -  name: print system information
       run: uname -a
    -  name: List
       run: ls
    -  name: List files
       run: ls -la
    -  name: show repository structure
       run: find .
  
  
    
