name: devops-company-site
env:
  WORKFLOW_VARIABLE: "iam workflow variable"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JOB_VARIABLE: "Iam job variable"
    steps:
      -  name: print workflow variable
         run: echo "$WORKFLOW_VARIABLE"
      -  name: print job variable
         run: echo "$JOB_VARIABLE"
      -  name: print step variable    
         env:
           STEPS_VARIABLE: "Iam steps variable"
         run: echo "${{env.STEPS_VARIABLE}}"
      -  name: print details
         run: |
           echo "$WORKFLOW_VARIABLE"
           echo "$JOB_VARIABLE"
           echo "$STEPS_VARIABLE"
    
      
